version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: 'YOUR API KEY'
      MODEL: 'wenxin'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ChatGPT测试群", "ChatGPT测试群2"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
      baidu_wenxin_api_key: 'vjHT3a5b9aMCK1p6da5GdxLZ'
      baidu_wenxin_secret_key: 'iADZIkwuhaHkfN0HkyFWj9j2pN3UppPq'
      "channel_type": "wechatcom_app",   
      "single_chat_prefix": [""],   
      "wechatcom_corp_id": "ww09f4a9599ec159cc",              
      "wechatcomapp_token": "RwuAGOTo7TSe",             
      "wechatcomapp_secret": "dEc0snAOI8GVLuoBGs088S43RwYIo_4dGruSj4z5XO4",           
      "wechatcomapp_agent_id": "1000003",          
      "wechatcomapp_aes_key": "raclDNNFt5kLNMfUQEpdmVmToJeLYnV66rT7xmzRtpZ",
      "wechatcomapp_port": 9898  